name: API CI

on:
  push:
    paths:
      - "api/**"
  pull_request:
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  api_test:
    name: API Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --fail-under 100
      - run: cargo fmt --all -- --check
